### ISSUE TITLE
[Add]호텔 및 객실 테이블에 레코드 삽입 및 객실 테이블 컬럼 추가

### ISSUE THREAD

**Issue by pywon128** [YuYoHan/myrealtrip#63]
hotels, hotelimg, rooms, roomimg 테이블에 레코드 삽입 및 rooms 테이블에 room_name, 컬럼 추가

도시 : 12개 - (뉴욕, 피렌체, 라스베이거스, 파리, 런던, 바르셀로나, 로마, 루체른, 인터라켄, 세고비아, 톨레도, 두바이)

도시당 호텔 : 5개 ( 호텔 메인사진 1개, 총 5개)
호텔당 객실 : 3개 ( 객실 메인사진 1개, 총 3개 )

추가될 쿼리 : 480개
예)
hotels
insert into hotels (hotel_name, hotel_location, hotel_info, admin_id) values('파크 레인 뉴욕', '36 Central Park S, New York, New York, 미국, 10019', '소개글', 3);
...

hotelimg
insert into hotelimg (hotel_img_url, hotel_id) values('https://dry7pvlp22cox.cloudfront.net/mrt-images-prod/2023/09/04/yrDp/8lQ3VvthdL.jpg?width=980&height=735&quality=90', 1);
...

rooms
insert into rooms (room_name, room_status, room_count, room_price, option_others, hotel_id) values('룸, 킹사이즈침대 1개 (Park Lane)', 'RESERVATION_O', 2, '339000', '킹사이즈침대 1개, 성인 2명, 객실 크기(㎡) - 33, 무료 유아용 침대, 타월 제공됨, 에어컨', 1);
...

roomimg
insert into roomimg(room_img_url, room_id) values('https://i.travelapi.com/lodging/1000000/10000/2800/2714/d1f4f691_z.jpg', 1);
...

**Comment by YuYoHan** [comment]
와 대박이네요! 화이팅~
